### ISSUE TITLE
must reload to find newly configured tables

### ISSUE THREAD

**Issue by toccata10** [mjrgh/PinballY#42] opened 2019-02-10 08:51 UTC
The situation:
1) I add a new vpx table (say Monte-Carlo) to my visual pinball/tables folder
2) in pinbally, I switch to "show unconfigured games", I edit the details.
3) the table Monte-Carlo still shows in the "unconfigured category": if I untick "show unconfigured games", I can't find them.
4) I have to quit pinbally and relaunch it: then, it's perfect.
It's a minor annoyance, but I wanted to report it.

**Comment by mjrgh** [comment] 2019-02-11 05:17
Note: to reproduce, "Hide unconfigured games in the main list" has to be selected in the options (under the "Game Wheel" page).

I'll fix it, but until then, you can work around it with an extra step:  after editing the game details and clicking OK to close the dialog, press the Left/Next Game button to switch to a different game.  Then you can switch back to the regular wheel display, and the game should show up.  

(The problem is that the program temporarily keeps the game marked as unconfigured after you close the Game Settings dialog, just until you switch to a different game.  At that point it sets the "configured" status in the game.  This is actually intentional - the reasoning is that it prevents the game from suddenly disappearing from view immediately after editing the details if you happen to have the "show unconfigured" filter active.  But switching to a different filter should also finalize the new "configured" status.)

**Comment by mjrgh** [comment] 2019-02-13 19:59
Should be fixed now (beta 6).

**Closed by mjrgh** 2019-02-13 19:59 UTC

**Comment by toccata10** [comment] 2019-02-14 09:07
Fixed. Thanks.
But with beta6, the unconfigured games only show a black-screen (instead of the generic wooden playfield).
![black-screen](https://user-images.githubusercontent.com/7478580/52775565-4a0e4480-3040-11e9-927b-496658f9ea98.JPG)

**Comment by mjrgh** [comment] 2019-02-14 19:14
> I think there's a problem with the assets folder (in beta 6): it's almost empty

That would probably be it - that's where the default image comes from.  Could you check that there's a subfolder called Videos?

Did you install from the MSI or ZIP?

**Comment by mjrgh** [comment] 2019-02-14 19:30
Okay, I'm betting you installed from the ZIP - I just took a look and I missed adding the restructured subfolders to it.  I just updated the release ZIPs to include the files, but I also uploaded a ZIP with just the missing files for you:

http://mjrnet.org/pinscape/downloads/PinballY/assets-20190213.zip
