### ISSUE TITLE
Pressing Exit while on loading screen loses focus

### ISSUE THREAD

**Issue by danfleck** [mjrgh/PinballY#79] opened 2019-09-01 23:13 UTC
When you launch a game from PinballY the loading screen appears. If you press Exit while on the loading screen you return to the PinballY menu screen, but without focus. In some cases the virtual pinball machine finishes loading and then shows up and sometimes it doesn't. Likely this depends on how "fast" you press exit after the loading begins.

**To Reproduce**
1. Startup PinballY
2. Launch a Visual Pinball X game using the launcher button (one press)
3. While the loading screen is showing press the Exit button
4. PinballY screen returns but without focus (can't switch games or relaunch)

**Expected behavior**
It would be nice if either the pinballY screen that shows up had focus and the pinballX game was killed or if the exit was simply disabled while loading to avoid the problem.

**Windows version**
Windows 10

**Additional context**
There is a workaround for the situation by waiting for the game to load and exiting it although I'm not sure if that will always work.  This isn't a big problem, but something my kid did and got confused.

**Comment by mjrgh** [comment] 2019-11-28 20:13
I haven't been quite able to reproduce the focus behavior, but as you said, that's probably a matter of timing.  But there's definitely some unpredictable behavior if you hit EXIT while the child process is in the middle of the launch, so I'm pretty sure your focus issues are related to that.  At any rate, I've made some changes for the next update to make the EXIT key work reliably during launch - hopefully making that work consistently will also fix the focus problems you're having.  I'll leave this open until you have a chance to test it, though, since it's hard to be certain I'm looking at the same thing without being able to reproduce the exact problem.

The changes will be in the beta 15, which should be available in the next few days.  Give it a try when it's out and let me know if it fixes this.

**Comment by mjrgh** [comment] 2020-01-02 04:57
After more playing around with it on Windows 7, I was finally able to hit the special timing to get the focus loss to happen.  I did some work in the Beta 18 to try to avoid that happening.  It's probably impossible to make it never ever ever happen, because focus on Windows is kind of inherently twitchy given that it is by design something that programs have to fight over, but I think it should be a lot more solid now.  

In addition, I added a new "Last Resort" feature to get focus back: if focus ever gets lost, press and hold the Exit Game button (usually mapped to Escape) for about three seconds.  That should force PinballY back into the foreground.  So hopefully that'll serve as a fallback for any remaining cases like this.

**Closed** 2020-01-02 04:57 UTC
