### ISSUE TITLE
Addressable leds (teensy) with PinballY

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinballY#50] opened 2019-03-14 02:33 UTC
Is PinballY able to use Addressable LEDs (DOF Teensy)?

I just installed an addressable led strip on each side of the playfield.
When I run a table (manually or by PinballY) my addressable LEDs works (and the LED on the Teensy flashes quickly).
But in PinballY nothing (the led on the Teensy flashes every two seconds).

**Comment by mjrgh** [comment] 2019-03-14 03:14
> Is PinballY able to use Addressable LEDs (DOF Teensy)?

Yes - the addressable LED collection is just a DOF device like any other.  

Go to the DOF config database (http://configtool.vpuniverse.com), log in, click the Table Configs tab, and select PinballY from the Table Name drop list.

The various "MX" devices are the addressable LEDs - PF Left Flashers MX, PF Left effects MX, etc.  

You'll have to look at the Port Assignments tab to see how you have your physical light strips mapped to those MX groups.  If you have left/right playfield strips, you probably have those configured as PF Left Effects MX and PF Right Effects MX.  

Back on the Table Config screen, those two MX groups don't have any effects mappings in the default config, which would explain why you're not seeing anything happening on the LEDs when running in PinballY.  That is, there's nothing programmed to happen on those devices in PinballY.

If you want to come up with some effects definitions for those, you can enter them in the right half of the Table Config screen.  Go through the normal process of saving changes, generating new .ini files, downloading the new .ini files, and installing the new downloaded .ini files in your DOF folder.  

Once you have some effects you like, you can click "Submit for public consideration" at the bottom of the form to request putting them into the default config.

**Comment by gate001** [comment] 2019-03-15 00:36
That's what I did, maybe I made a mistake in my instruction in the configtool. I used TerryRed's Excel sheet.
I did another test with simpler instructions:

PF Left Effects MX:
$PBYFlipperLeft Yellow MAX200 AH100 ADU AS400 Blink 50

PF Right Effects MX:
$PBYFlipperRight Yellow

Nothing in PinballY! but when I run a table my leds work.

**Comment by mjrgh** [comment] 2019-03-15 00:45
Do you have any other DOF devices apart from the LED strips, or is that it?  In other words, have you confirmed that DOF is working **at all** in PinballY?  

If DOF + PinballY works for other devices, I'd focus on the DOF configuration - for example, make sure you really have the updated .ini file installed and so on.

If you don't have any other devices, I'd confirm that PBY is connecting to DOF in the first place.   Make sure the DirectOutput box is checked in the Log File section in the options dialog and make sure "Enable DOF effects" is checked in the DOF section of the options.  Exit the program, do a fresh run, exit again.  Check the PinballY log file (PinballY.log) to see what it says about DOF setup.  Check that a DirectOutput.log file exists in the same folder, and check it for error messages.

**Comment by gate001** [comment] 2019-03-15 01:57
Pinbally + DOF works fine, all other devices work in PinballY, only my addressable led do not work.
When you say "make sure you really have the updated .ini file installed", are you talking of the directoutputconfig30.ini and the directoutputconfig51.ini files from the DOFconfigtool?

**Comment by mjrgh** [comment] 2019-03-15 03:02
> Pinbally + DOF works fine, all other devices work in PinballY, only my 
> addressable led do not work.

Okay, if other devices are working then DOF must be getting initialized successfully.

> When you say "make sure you really have the updated .ini file installed", 
> are you talking of the directoutputconfig30.ini and the directoutputconfig51.ini 
> files from the DOFconfigtool?

Right - exactly.  To be sure that DOF is actually seeing the new effects you added.

I guess the next thing to look at is the DOF log - DirectOutput.log, should be in your PinballY folder.  Go over the contents carefully and see if there's any clue there.  Some things in particular you can look for:

-  It should list the full paths to all of the .ini files it's loading, so you can confirm they're at the locations and names you expect

- "EXCEPTION:" messages

- Make sure it's finding and connecting to your LED controller.

**Comment by gate001** [comment] 2019-03-15 10:01
I looked at the DirectOutput.log, there is an error:

2019.03.14 19:04:52.120	Global config filename is "C:\DirectOutput\config\GlobalConfig_PinballY.xml"
2019.03.14 19:04:52.123	Global config file "C:\DirectOutput\config\GlobalConfig_PinballY.xml" does not exist; no global config loaded

Is there a parameter in PinballY that I have to change to load my GlobalConfig_B2SServer.xml file?
Or do I have to copy and rename my GlobalConfig_B2SServer.xml file to GlobalConfig_PinballY.xml?

**Comment by mjrgh** [comment] 2019-03-15 18:35
Oh, right, I should have thought of that!  I totally forgot about that little DOF detail.  Yes, you should be able to just copy your GlobalConfig_B2SServer.xml to GlobalConfig_PinballY.xml.   

There's no parameter for this; DOF by design just uses a separate global config file for each host program.  (I guess "global config" is a misnomer - it should be called the "program config file".)

I never think about this myself because the global config for the most part isn't needed.  But it **is** critical if you have LED strips, since DOF can't discover those on its own.  It needs the global config file to tell it where the cabinet config file is so that it can set up the Teensy connection.

**Comment by gate001** [comment] 2019-03-16 02:14
It was an user problem, not a PinballY problem. All Work well, it was really my missing GlobalConfig_PinballY.xml file.

At the next release, can you add a state in PinballY during the startup video. I would like to add some light with my leds during the startup video.

**Comment by mjrgh** [comment] 2019-03-16 03:55
Glad you got it sorted out.  I added a note to the install help about the global config - hopefully I'll remember it faster next time someone runs into it.

> At the next release, can you add a state in PinballY during the startup video. 

Sounds like a good addition. I'll put it on my list.

**Closed by mjrgh** 2019-03-16 03:55 UTC
