### ISSUE TITLE
Error 0xc000007b when I start Pinbally 64 bit

### ISSUE THREAD

**Issue by RoelHermus** [mjrgh/PinballY#31] opened 2019-01-25 22:07 UTC
Today I've installed  the 64bit January 22, 2019 update. The next step, trying the new PinballY gives me a direct error 0xc000007b and the program stops. Searching the internet for a solution, removing end reinstall, clean up the registry, check the disk and lots of more try's. Nothing fixed the problem. I took a break for couple of hours. After the break I try a some new things, but nothing. But latest idea was to install the 32 bit version in a different folder: pinbally32. After that both version works perfect. I 'm confused what the problem is, but it's solved.

**Comment by mjrgh** [comment] 2019-01-26 01:32
Have you run past 64-bit versions successfully, or is this the first version you've tried?

From what I can find about this error, it's usually caused by corrupted Windows system files.  If you do a Web search you'll be able to find lots of "how to" advice for random things to try that *might* fix it, although unfortunately I can't find anything that's very helpful in explaining what actually causes the problem other than some Microsoft support threads that refer vaguely to corrupted user accounts or corrupted system files.

One possible source of trouble that seems to be frequently mentioned is video drivers, so you might try updating those.  

Sorry I don't have anything more concrete to try.  I haven't heard of this before and everything I can find on the Web is just like typical information on the Web, which is to say vague and probably mostly false.

**Comment by mjrgh** [comment] 2019-01-26 01:34
By the way, one thing I **wouldn't** try that a couple of the Web articles suggest is "run in Admin mode".  I always, always, always discourage that as a random troubleshooting tactic.  It's just asking for more trouble from other conflicts, so please ignore any "run in Admin mode" advice you come across.

**Comment by mjrgh** [comment] 2019-01-26 07:11
One more thought:  one thing that can trigger this error is a "bit" mismatch between a 64-bit application and 32-bit DLLs.  You might try installing the **full** 64-bit version in a new, empty folder, being sure to use the full installer, not the "minimal update" installer.  Just to make sure you don't have any old DLL files hanging around from a past install.

**Comment by RoelHermus** [comment] 2019-01-26 08:14
I've a seperate pc with two screens for playing pinball. I use PinballY the for  2 months or longer, without problems. Yesterday I tryed the new version of PinballY and get the error.
The operating system is Windows 10, version 1809. The only things changed on the pc are the updated of Windows 10 and Google chrome. I did not run in admin mode and I tryed also an absolute clean installation.  Not a big issue because PinballY works fine again. But I tell it to you, only  to let you know. So far so good! If I find the solution, or the thing I did wrong, I let you know.

**Comment by RoelHermus** [comment] 2019-01-26 09:11
Perhaps this point: I'm using Windows 10N. In this version is a part of the media software not installed. With the previous PinballY I got the MFPLAT.DDL not installed error. I found the dll on an other pc and copy it in the PinballY folder. After that PinballY works perfect. Maybe was this solution too simple. I removed the dll, and the missing dll error comes back. After installing the microsoft KB413255 PinballY works fine again. I guess this is a better solution....?

**Comment by mjrgh** [comment] 2019-01-26 22:40
> With the previous PinballY I got the MFPLAT.DDL not installed error. 
> I found the dll on an other pc and copy it in the PinballY folder.

Ah, I think this explains it!  

Let me guess that the full sequence of events was something like this:

1. You installed the previous **32-bit** PinballY in some folder, let's call it C:\PinballY
2. You updated Windows at some point and ran into the missing MFPLAT.DLL error
3. You copied MFPLAT.DLL from the other machine into the C:\PinballY folder
4. Everything was working again, until...
5. You updated to the new **64-bit** PinballY in the same folder
6. At which point you got that extremely unhelpful 0xc000007b error from Windows whenever you tried to run PinballY.exe

Is that close to accurate?

I think what happened is that the MFPLAT.DLL you copied from the other machine is the **32-bit** version of the DLL.  That will work just great as long as you're using 32-bit PinballY.exe.  When  you switched to the 64-bit PinballY.exe, though, Windows tries to load that same DLL file, discovers that it's a 32-bit DLL, and flies into a panic because of the 64/32-bit version clash.  One of the cardinal rules of 64-bit Windows is that a 64-bit EXE can only load 64-bit DLLs (and likewise, a 32-bit EXE can only load 32-bit DLLs).  But when they came up with this rule, they didn't bother coming up with a naming convention or anything like that to tell them apart.  For system DLLs like MFPLAT.DLL, they expect you to have **both** 32 and 64 bit versions installed, with the same filename, and they tell which is which by path - specifically, 64-bit MFPLAT.DLL is expected to be in C:\Windows\System32, and 32-bit MFPLAT.DLL is expected to be in C:\Windows\SysWow64.  (How's that for confusing?  64-bit goes in System32, 32-bit goes in SysWow64!)

When you copied that 32-bit MFPLAT.DLL into your PinballY folder, it prevented Windows from looking in the normal system folders, since Windows looks in the EXE's own folder first.

I'm guessing that the KB413255 patch you installed restored sanity by copying the 32- and 64-bit versions of MFPLAT.DLL into those two C:\Windows\... folders where Windows normally looks for them.

So everything's working now for you, both 32- and 64-bit versions?

**Comment by RoelHermus** [comment] 2019-01-26 23:06
Yes, you guess point 1 - 6 correct. In the Windows 10N version the media software is less complete as in the normal Windows 10 version. The KB413255 instal the missing media software and make it the same as the standard Windows 10. But the error message  0xc000007b is complete useless, maybe can you make a check in your software to handle this kind of problem. (I guess I ask too much now). I'm very happy with PinballY, now it works perfect. Thank you very much for the program and your time to read my issues.

**Comment by mjrgh** [comment] 2019-01-26 23:40
> But the error message 0xc000007b is complete useless

You're absolutely right about that!

> maybe can you make a check in your software to handle this kind of problem. 

I wish I could, but unfortunately I don't think there's any way to do that.  (Unless Microsoft wants to give me access to the Windows source code. :))  The problem is that this message is coming directly from the Windows EXE loader, **before** the program starts running.  Windows tries to load and resolve all of the DLL references embedded in the EXE file as part of the loading process, and this error occurs during that.

At least now that we understand what causes this error, I might be able to remember what it means the next time someone runs into it and be able to be a little more helpful in resolving it.

**Closed** 2019-01-26 23:41 UTC
