### ISSUE TITLE
Transparency png

### ISSUE THREAD

**Issue by mbaudouin** [mjrgh/PinballY#67] opened 2019-04-14 09:35 UTC
Hi,
the transparency of png images is represented with squares.

![2019-04-14 11_32_58-Window](https://user-images.githubusercontent.com/1648815/56090981-43b61080-5ea9-11e9-82f0-f39aa10b177c.png)

**Comment by mjrgh** [comment] 2019-04-14 17:53
Sorry, I have no idea what you're getting at.

**Comment by mbaudouin** [comment] 2019-04-14 18:14
Presentation of the tables is bad when the PNG includes transparency

**Comment by mjrgh** [comment] 2019-04-14 18:41
I'm really not sure what I'm looking at here.  

Maybe if you could attach a test file, and explain exactly how you're using it?  (Have you read https://github.com/mjrgh/PinballY/wiki/How-to-write-a-good-bug-report in the wiki?)

**Comment by mbaudouin** [comment] 2019-04-14 18:48
![Sans titre](https://user-images.githubusercontent.com/1648815/56097575-a08be800-5ef6-11e9-98ed-722fd33f165f.jpg)

**Comment by mjrgh** [comment] 2019-04-14 19:26
I see the screen shot, but perhaps you meant to upload a test file too?

**Comment by mbaudouin** [comment] 2019-04-14 19:36
![Cactus Canyon (Midway 1998)](https://user-images.githubusercontent.com/1648815/56098103-332f8580-5efd-11e9-954c-6ade0a103354.png)

**Comment by mjrgh** [comment] 2019-04-14 19:51
That image doesn't have any transparency.  Are you sure that's the one you intended to upload?  Maybe you meant to upload the wheel image instead?

**Comment by mbaudouin** [comment] 2019-04-14 19:59
it's the original. you can reproduce with that one. (may be not a problem with transparency?).

**Comment by mjrgh** [comment] 2019-04-14 20:46
Sorry, no.

Try this:  Exit the program.  Delete the WHEEL IMAGE (or simply rename it so that it won't be found.)  Run the program.  What do you see?

**Comment by mbaudouin** [comment] 2019-04-15 17:25
Same PB if i delete the Wheel.
NOTE :  if I rotate display, The image is good. I think it's caused by the resizing.
my screen = 1650x1050  // image = 1920x1080
image heigth (1920) is streched to fit 1050.

**Comment by mjrgh** [comment] 2019-07-09 22:13
One thing that might be worth noting is that the source image you uploaded is using a half-tone pattern for some of the color areas you're having problems with.  Take a look at this close-up segment extracted from the image you uploaded:

![ZoomedInCactusCanyon](https://user-images.githubusercontent.com/8271213/60926302-f3a5da80-a25a-11e9-82cb-d61dc5df38d8.png)

You said that you're stretching this 1920x1080 image to 1650x1050.  Resizing tends to add some artifacts, especially with half-tone patterns like this.  Here's that same zoomed-in area after resizing in Paint Shop Pro with bilinear interpolation:

![ResizedZoomedInCactusCanyon](https://user-images.githubusercontent.com/8271213/60926552-be4dbc80-a25b-11e9-929a-0db7bd85b4f1.png)

Suggestions:

1. Try capturing a live screen shot of the game using the Capture Media function.  That should give you a higher-quality image to start with, which will make it less visibly affected by resizing; plus it'll be captured at the native size of your monitor, so it won't have to be resized in the first place.

2. If you really want to keep using this particular image, try resizing it in your favorite image editor to match your monitor size, and save it at the new size.  A photo editor will give you more options for resampling the pixels to the new size to help you smooth out the half-tone artifacts.

**Comment by mjrgh** [comment] 2019-11-28 21:04
I'm going to close this out, as it's rather old and I was never able to reproduce quite what you were seeing.  I think the artifacts you were seeing might have been related to sRGB color space used in some of your sample images, which is handled better in the beta 15.

**Closed by mjrgh** 2019-11-28 21:04 UTC
