### ISSUE TITLE
Audio Not playing during table browsing

### ISSUE THREAD

**Issue by starwyvern** [mjrgh/PinballY#116] opened 2020-02-08 22:47 UTC
mjr,

Here is the audio file that isn't playing during table selection.
[Audio File.zip](https://github.com/mjrgh/PinballY/files/4175474/Audio.File.zip)

**Comment by mjrgh** [comment] 2020-02-25 21:17
Thanks for the test case.  It looks like DirectShow (the Microsoft subsystem that we're using right now to play back MP3 files) is just too old for the encoding format used in this file.  I'm going to move the MP3 playback over to libvlc instead, since it's more modern and is being actively developed and supported (unlike DShow).  I confirmed that this file plays back fine with libvlc, so moving to the new codecs should fix this and any other MP3's that haven't been playing back under DShow.   (And it's better to use libvlc anyway, since we're already incorporating it for video playback; so this change will have the nice side effect of eliminating an external dependency, and one that Microsoft considers obsolete at that.)

**Comment by starwyvern** [comment] 2020-02-25 21:21
Thanks for looking into it! Will that be an update to Pinball Y? Other MP3s I put in the table audio get the same error as well.

**Comment by mjrgh** [comment] 2020-02-25 21:21
Yes, it'll be in the next update.

**Comment by mjrgh** [comment] 2020-02-26 03:43
The Beta 21 has the new libvlc playback - that should fix it.

**Closed by mjrgh** 2020-02-26 03:43 UTC
